apiVersion: apps/v1
kind: Deployment
metadata:
  name: dans-v1fs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1fs-app
  template:
    metadata:
      labels:
        app: v1fs-app
    spec:
      containers:
      - name: dans-v1fs
        image: 3137cbf
        ports:
        - containerPort: 80
