name: Spin Up EC2 Instance and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: SSH and Deploy Application to Instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-21-247-90.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          protocol: tcp
          timeout: 60s
          command_timeout: 10m
